### ISSUE TITLE
Allow Cancellation of the UDPIH Gadget at everytime

### ISSUE THREAD

**Issue by YamaBanana** [GaryOderNichts/udpih_nxpayload#2]
It is extremely annoying to wait until the Gadget allows me to leave after an failed attempt. Ik this is not the proper way to write an issue, but this just drove me so mad, that I had to leave this feedback. Would be nice if you could fix that (if technically possible). Seeya.

**Comment by GaryOderNichts** [comment]
Pressing the volume up and down buttons at the same time allows you to cancel.

**Comment by YamaBanana** [comment]
Yeah, was just about to Edit the Issue. I didnt read that you have to hold them instead of just pressing them. So yeah, would be helpful if I do stuff like this without being awake for days.....

Anyway, have a nice Day.
